- app/controllers/quizzes_controller.rb
- app/views/quizzes/_form.html.erb
- app/views/quizzes/new.html.erb
- config/routes.rb
- db/migrate/20230523030947_rename_number_of_question_in_quiz_name.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/quizzes_controller_test.rb
First quiz controller version and update quiz schema
> quiz-controller-1

- Gemfile.lock
- app/models/question.rb
- db/seeds.rb
> updated the db

- Gemfile.lock
- app/models/question.rb
- db/migrate/20230523040832_add_score_and_total_correct_to_questions.rb
- db/schema.rb
- db/seeds.rb
updated the seed with 2 new columns
> Updating seed

- app/controllers/questions_controller.rb
- db/migrate/20230523050931_remove_total_correct_from_questions.rb
- db/migrate/20230523051157_add_total_correct_and_total_score_to_quizzes.rb
- db/migrate/20230523051238_remove_result_from_quizzes.rb
- db/migrate/20230523052147_remove_total_score_from_quizzes.rb
- db/migrate/20230523052223_add_total_points_to_quizzes.rb
- db/migrate/20230523052408_remove_total_correct_from_quizzes.rb
- db/schema.rb
- test/controllers/questions_controller_test.rb
updated the DB with new columns
> updated the schema

- app/controllers/questions_controller.rb
- db/migrate/20230523054647_add_correct_to_questions.rb
- db/schema.rb
added a new column to the questions table
> reupdated the schema

- db/migrate/20230523055427_remove_correct_from_questions.rb
- db/migrate/20230523055709_add_corrected_to_questions.rb
- db/schema.rb
> reupdated the schema again

- app/views/shared/_navbar3.html.erb
- config/tailwind.config.js
- db/schema.rb
- package.json
- yarn.lock
> trying to get flowbite to work

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
Added dependencies for the heatmap
> adding a heatmap

- app/views/interests/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar2.html.erb
- app/views/shared/_navbar3.html.erb
- db/schema.rb
> designed the first draft of the interests index

- app/views/interests/index.html.erb
- db/schema.rb
> working on the interest index

- app/models/interest.rb
is now prompting openai for 2 questions with 4 options each. The questions and options are created and assigned respectively.
> creating an interest 

- app/models/question.rb
- app/views/interests/index.html.erb
- app/views/quizzes/questions/show.html.erb
- app/views/shared/_navbar3.html.erb
> small fixes

- Gemfile
- app/views/interests/index.html.erb
> small changes

- app/views/interests/index.html.erb
- app/views/quizzes/questions/show.html.erb
- db/seeds.rb
> changed the look of the quiz

- app/views/interests/show.html.erb
done with the interest show page :))
> Interest show page

- app/views/interests/index.html.erb
> changed the url path

- app/controllers/interests_controller.rb
- app/models/interest.rb
- app/models/option.rb
- app/views/interests/index.html.erb
- config/environments/development.rb
made changes in the model, disabled Bullet, and made changes to the main page
> made changes

- app/views/quizzes/questions/show.html.erb
- app/views/quizzes/show.html.erb
- config/application.rb
> fixed the quiz logic

- app/controllers/quizzes/questions_controller.rb
- app/views/interests/index.html.erb
- app/views/quizzes/questions/show.html.erb
- app/views/quizzes/show.html.erb
small changes to the quiz logic
> changes to the quiz

- app/controllers/challenges_controller.rb
- app/views/challenges/show.html.erb
- app/views/quizzes/questions/show.html.erb
- app/views/quizzes/show.html.erb
- db/schema.rb
> fixes after merge

- app/views/interests/index.html.erb
> made little changes

- app/views/quizzes/show.html.erb
will continue to work on it later
> pushing to work on other stuff

- app/javascript/controllers/bar_chart_controller.js
- app/views/challenges/show.html.erb
- app/views/interests/index.html.erb
- app/views/layouts/application.html.erb
- app/views/quizzes/questions/show.html.erb
- app/views/shared/_navbar2.html.erb
- app/views/shared/_navbar3.html.erb
- config/tailwind.config.js
- package.json
- yarn.lock
Fixed a progress bar and removed daisy ui
> Quiz progress

- app/views/layouts/application.html.erb
- app/views/quizzes/show.html.erb
- config/tailwind.config.js
> almost done designing it

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_question.scss
- app/javascript/controllers/hello_controller.js
- app/views/challenges/show.html.erb
Done with the logic, need some styling
> Flip logic

- app/javascript/controllers/menu_controller.js
- app/views/challenges/show.html.erb
- app/views/interests/index.html.erb
- app/views/shared/_navbar2.html.erb
> quiz design

- app/views/interests/index.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/quizzes/show.html.erb
- config/tailwind.config.js
- db/schema.rb
changed fonts and minor details
> pushing style changes

- app/views/interests/show.html.erb
> added js to interest menu

- app/controllers/interests_controller.rb
minor change, adding photo to interest
> added photo to interest controller

- app/controllers/interests_controller.rb
- app/models/interest.rb
- app/views/interests/index.html.erb
fixed the cloudinary upload for interests
> added photos with cloudinary

- app/controllers/interests_controller.rb
- app/policies/interest_policy.rb
- app/views/interests/show.html.erb
- config/routes.rb
> added upload for picture

- app/views/devise/confirmations/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
fixed the looks of the sign in / sign out
> fixed the login logout menues

- app/views/interests/index.html.erb
- app/views/quizzes/index.html.erb
fixed the index on larger screens
> small fixes on the index page
